version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "app.py", "--host", "0.0.0.0"]

  frontend:
    build: ./yudi-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./yudi-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:5000
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host"]
